dataprocessor:
    type: default
    sampling_stopping_strategy: first_exhausted
    seed: 66
datasets:
  - name: dataset_1
    sampling: 1
    data_paths:
      - "/fastdata/amal_intern/workspace/fms-hf-tuning/tests/artifacts/testdata/jsonl/twitter_complaints_input_output.jsonl"
    data_handlers:
      - name: tokenize_and_apply_input_masking
        arguments:
          remove_columns: all
          batched: false
          fn_kwargs:
            input_column_name: input
            output_column_name: output
  - name: dataset_2
    sampling: 1
    data_paths:
      - "/fastdata/amal_intern/workspace/fms-hf-tuning/tests/artifacts/testdata/jsonl/twitter_complaints_input_output.jsonl"
    data_handlers:
      - name: tokenize_and_apply_input_masking
        arguments:
          remove_columns: all
          batched: false
          fn_kwargs:
            input_column_name: input
            output_column_name: output